name: "Alex's Blog"
description: "Ruby, sinatra, javscript: All the funs"
author: "Alex B"
nick: "ZucchiniZe"
author-bio: "I am a human who goes to high school who also likes to create small trinkets for the web using nodejs, react, ruby and sinatra."

url: "https://alexb.ninja"
baseurl: "/blog"

twitter: ZucchiniZe
github: ZucchiniZe
githuburl: http://github.com/ZucchiniZe/blog

segment_key: "gavGcxDFOuUa5eqYoQ6ieHGllSQUptXv"

markdown: kramdown
kramdown:
  input: GFM
permalink: /:month/:day/:title
highlighter: pygments

paginate: 10
paginate_path: "/p/:num"

sass:
  sass_dir: _scss
  style: :compressed

gems:
  - jemoji
  - jekyll-sitemap
